model:
    arch: frrnB
data:
    dataset: cityscapes
    train_split: train
    val_split: val
    img_rows: 512
    img_cols: 1024
    path: /vol/research/chewing/shProject/gradSet/finalGrad
training:
    train_iters: 25000
    batch_size: 2
    val_interval: 500
    print_interval: 25
    optimizer:
        lr: 1.0e-4
        name: adam
    lr_schedule:
        name: poly_lr
        max_iter: 25000
    momentum: 0.99
    weight_decay: 0.0005
    resume: frrnB_cityscapes_best_model.pkl
    visdom: False
    n_workers: 2
    loss:
        name: cross_entropy
#
#model:
#    arch: frrnB
#data:
#    dataset: cityscapes
#    train_split: train
#    val_split: val
#    img_rows: 512
#    img_cols: 1024
#    path: /private/home/meetshah/misc_code/ps/data/VOCdevkit/VOC2012/
#training:
#    train_iters: 85000
#    batch_size: 2
#    val_interval: 500
#    print_interval: 25
#    optimizer:
#        lr: 1.0e-4
#    l_rate: 1.0e-4
#    l_schedule:
#    momentum: 0.99
#    weight_decay: 0.0005
#    resume: frrnB_cityscapes_best_model.pkl
#    visdom: False
