model:
    arch: frrnB
data:
    dataset: cityscapes
    train_split: train
    val_split: val
    img_rows: 512
    img_cols: 1024
path: /home/weaver/PycharmProjects/gradSemSeg/gradset
training:
    train_iters: 30000
    batch_size: 2
    val_interval: 500
    print_interval: 25
    optimizer:
        lr: 1.0e-4
        name: adam
    lr_schedule:
        name: poly_lr
        max_iter: 30000
    momentum: 0.99
    weight_decay: 0.0005
#    resume: frrnB_cityscapes_best_model.pkl
    visdom: False
    n_workers: 2
    loss:
        name: cross_entropy


#   path 
#	|
#	--leftImg8bit
#	|     |
#	|     |--train
#	|     |
#	|     |--val
#	|
#	--gtFine
#	      |
#	      |--train
#	      |
#	      |--val
